dist: bionic
language: java
sudo: required
addons:
  chrome: stable
  firefox: latest
services:
  - xvfb
jdk:
  - openjdk8
  - openjdk11
  - oraclejdk8
  - oraclejdk11
env:
  - JAVA_OPTS=-Dfile.encoding=cp1252
  - JAVA_OPTS=-Dfile.encoding=UTF-8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start || echo \"Unable to start virtual display.\""
  - sleep 3
  - nvm i node
install:
  - npm i -g testcafe
before_script:
  - fluxbox >/dev/null 2>&1 &
  - sleep 5
script:
  - ./gradlew clean check
  - ./gradlew :startE2eTestServer &
  - sleep 5
  - testcafe 'chrome --user-data-dir $(pwd)/testcafe/chrome' testcafe/test.js --hostname localhost --ports 12345,54321 --skip-js-errors
  - testcafe 'firefox -profile $(pwd)/testcafe/firefox' testcafe/test.js --hostname localhost --ports 12345,54321
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - node_modules
