language: java
sudo: required
jdk:
  - openjdk8
  - openjdk11
  - oraclejdk8
  - oraclejdk11
env:
  - JAVA_OPTS=-Dfile.encoding=cp1252
  - JAVA_OPTS=-Dfile.encoding=UTF-8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
before_install:
  - nvm i node
install:
  - npm install github:GoogleChromeLabs/web-push-testing-service -g
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start || echo \"Unable to start virtual display.\""
  - sleep 3
script:
  - web-push-testing-service start wpts
  - ./gradlew clean check
  - web-push-testing-service stop wpts
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - ~/.selenium-assistant
    - node_modules
