dist: trusty

language: java

jdk:
  - oraclejdk8

before_install:
  - nvm install node

install:
  - npm install web-push-testing-service@0.3.2 -g
    #  - npm install https://github.com/GoogleChrome/web-push-testing-service.git#42c763d6c32b579715a05c8addfddad5529ef152 -g

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start || echo \"Unable to start virtual display.\""
  - sleep 3

script:
  - web-push-testing-service start wpts
  - ./gradlew test
  - web-push-testing-service stop wpts

env:
  - JAVA_OPTS=-Dfile.encoding=cp1252
  - JAVA_OPTS=-Dfile.encoding=UTF-8
