dist: trusty

sudo: required

language: java

jdk:
  - openjdk7
  - oraclejdk8

env:
  - JAVA_OPTS=-Dfile.encoding=cp1252
  - JAVA_OPTS=-Dfile.encoding=UTF-8

before_install:
  - nvm install node

install:
  - npm install web-push-testing-service@0.4.0 -g

before_script:
  - sudo sed -i 's/security.provider.9/#security.provider.9/g' $JAVA_HOME/jre/lib/security/java.security
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start || echo \"Unable to start virtual display.\""
  - sleep 3

script:
  - web-push-testing-service start wpts
  - ./gradlew test
  - web-push-testing-service stop wpts

